// Mock data for demo purposes - Expanded for impressive demo
export const mockContracts = [
  {
    id: '1',
    vendor: 'Stripe',
    contract_type: 'Terms of Service',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-12-10T14:30:00Z',
    status: 'active',
    versions_count: 3,
    high_risk_changes: 2,
    last_review_date: '2024-12-10T14:30:00Z',
    next_review_date: '2025-01-10T00:00:00Z',
    vendor_risk_score: 72,
  },
  {
    id: '2',
    vendor: 'AWS',
    contract_type: 'Service Agreement',
    created_at: '2024-02-20T09:00:00Z',
    updated_at: '2024-12-15T11:20:00Z',
    status: 'active',
    versions_count: 5,
    high_risk_changes: 1,
    last_review_date: '2024-12-15T11:20:00Z',
    next_review_date: '2025-01-15T00:00:00Z',
    vendor_risk_score: 45,
  },
  {
    id: '3',
    vendor: 'Google Cloud',
    contract_type: 'Privacy Policy',
    created_at: '2024-03-10T08:00:00Z',
    updated_at: '2024-11-30T16:45:00Z',
    status: 'active',
    versions_count: 2,
    high_risk_changes: 0,
    last_review_date: '2024-11-30T16:45:00Z',
    next_review_date: '2024-12-30T00:00:00Z',
    vendor_risk_score: 28,
  },
  {
    id: '4',
    vendor: 'Slack',
    contract_type: 'Data Processing Agreement',
    created_at: '2024-04-05T12:00:00Z',
    updated_at: '2024-12-01T09:15:00Z',
    status: 'active',
    versions_count: 4,
    high_risk_changes: 3,
    last_review_date: '2024-12-01T09:15:00Z',
    next_review_date: '2025-01-01T00:00:00Z',
    vendor_risk_score: 88,
  },
  {
    id: '5',
    vendor: 'Salesforce',
    contract_type: 'Master Subscription Agreement',
    created_at: '2024-05-12T14:00:00Z',
    updated_at: '2024-11-28T10:30:00Z',
    status: 'active',
    versions_count: 3,
    high_risk_changes: 1,
    last_review_date: '2024-11-28T10:30:00Z',
    next_review_date: '2024-12-28T00:00:00Z',
    vendor_risk_score: 52,
  },
  {
    id: '6',
    vendor: 'MongoDB Atlas',
    contract_type: 'Terms of Service',
    created_at: '2024-06-18T09:00:00Z',
    updated_at: '2024-12-05T15:20:00Z',
    status: 'active',
    versions_count: 2,
    high_risk_changes: 2,
    last_review_date: '2024-12-05T15:20:00Z',
    next_review_date: '2025-01-05T00:00:00Z',
    vendor_risk_score: 65,
  },
  {
    id: '7',
    vendor: 'Twilio',
    contract_type: 'Acceptable Use Policy',
    created_at: '2024-07-22T11:00:00Z',
    updated_at: '2024-12-12T08:45:00Z',
    status: 'active',
    versions_count: 4,
    high_risk_changes: 0,
    last_review_date: '2024-12-12T08:45:00Z',
    next_review_date: '2025-01-12T00:00:00Z',
    vendor_risk_score: 35,
  },
  {
    id: '8',
    vendor: 'Zendesk',
    contract_type: 'Service Level Agreement',
    created_at: '2024-08-30T13:00:00Z',
    updated_at: '2024-11-25T16:00:00Z',
    status: 'active',
    versions_count: 2,
    high_risk_changes: 1,
    last_review_date: '2024-11-25T16:00:00Z',
    next_review_date: '2024-12-25T00:00:00Z',
    vendor_risk_score: 48,
  },
  {
    id: '9',
    vendor: 'Datadog',
    contract_type: 'Privacy Policy',
    created_at: '2024-09-14T10:00:00Z',
    updated_at: '2024-12-08T12:30:00Z',
    status: 'active',
    versions_count: 3,
    high_risk_changes: 0,
    last_review_date: '2024-12-08T12:30:00Z',
    next_review_date: '2025-01-08T00:00:00Z',
    vendor_risk_score: 32,
  },
  {
    id: '10',
    vendor: 'Auth0',
    contract_type: 'Data Processing Agreement',
    created_at: '2024-10-20T15:00:00Z',
    updated_at: '2024-12-14T09:00:00Z',
    status: 'active',
    versions_count: 2,
    high_risk_changes: 1,
    last_review_date: '2024-12-14T09:00:00Z',
    next_review_date: '2025-01-14T00:00:00Z',
    vendor_risk_score: 58,
  },
];

export const mockVersions = {
  '1': [
    {
      id: 'v1-1',
      contract_id: '1',
      version_number: 1,
      source_type: 'url',
      source_url: 'https://stripe.com/legal/tos',
      created_at: '2024-01-15T10:00:00Z',
    },
    {
      id: 'v1-2',
      contract_id: '1',
      version_number: 2,
      source_type: 'url',
      source_url: 'https://stripe.com/legal/tos',
      created_at: '2024-06-20T14:00:00Z',
    },
    {
      id: 'v1-3',
      contract_id: '1',
      version_number: 3,
      source_type: 'url',
      source_url: 'https://stripe.com/legal/tos',
      created_at: '2024-12-10T14:30:00Z',
    },
  ],
};

export const mockChanges = {
  '1': [
    {
      id: 'c1',
      contract_id: '1',
      change_type: 'modified',
      clause_category: 'liability',
      old_text: 'Stripe\'s liability is limited to the amount paid in the last 12 months.',
      new_text: 'Stripe\'s liability is limited to the amount paid in the last 6 months.',
      similarity_score: 0.75,
      risk_level: 'high',
      risk_score: 85,
      explanation: 'This change significantly reduces the liability cap from 12 months to 6 months, potentially limiting your recourse in case of service failures or data breaches.',
      detected_at: '2024-12-10T14:30:00Z',
    },
    {
      id: 'c2',
      contract_id: '1',
      change_type: 'added',
      clause_category: 'data_usage',
      old_text: '',
      new_text: 'Stripe may use aggregated transaction data for machine learning and fraud detection purposes.',
      similarity_score: 0,
      risk_level: 'high',
      risk_score: 78,
      explanation: 'New clause allows Stripe to use your transaction data for ML purposes. While aggregated, this expands their data usage rights beyond the original agreement.',
      detected_at: '2024-12-10T14:30:00Z',
    },
    {
      id: 'c3',
      contract_id: '1',
      change_type: 'modified',
      clause_category: 'termination',
      old_text: 'Either party may terminate with 60 days notice.',
      new_text: 'Either party may terminate with 30 days notice.',
      similarity_score: 0.82,
      risk_level: 'medium',
      risk_score: 45,
      explanation: 'Termination notice period reduced from 60 to 30 days. This gives you less time to migrate if Stripe decides to terminate.',
      detected_at: '2024-12-10T14:30:00Z',
    },
    {
      id: 'c4',
      contract_id: '1',
      change_type: 'removed',
      clause_category: 'service_level',
      old_text: 'Stripe guarantees 99.9% uptime with credits for downtime exceeding this threshold.',
      new_text: '',
      similarity_score: 0,
      risk_level: 'critical',
      risk_score: 92,
      explanation: 'The SLA guarantee has been completely removed. You no longer have contractual recourse for service outages or downtime.',
      detected_at: '2024-12-10T14:30:00Z',
    },
  ],
  '2': [
    {
      id: 'c5',
      contract_id: '2',
      change_type: 'modified',
      clause_category: 'payment',
      old_text: 'Pricing changes require 90 days advance notice.',
      new_text: 'Pricing changes require 30 days advance notice.',
      similarity_score: 0.78,
      risk_level: 'high',
      risk_score: 72,
      explanation: 'AWS can now change pricing with much shorter notice (30 vs 90 days), reducing your ability to plan budget and potentially migrate.',
      detected_at: '2024-12-15T11:20:00Z',
    },
  ],
  '4': [
    {
      id: 'c6',
      contract_id: '4',
      change_type: 'added',
      clause_category: 'data_usage',
      old_text: '',
      new_text: 'Slack may share anonymized usage data with third-party analytics providers.',
      similarity_score: 0,
      risk_level: 'high',
      risk_score: 68,
      explanation: 'New data sharing clause allows Slack to share your usage patterns with third parties, even if anonymized.',
      detected_at: '2024-12-01T09:15:00Z',
    },
    {
      id: 'c7',
      contract_id: '4',
      change_type: 'modified',
      clause_category: 'intellectual_property',
      old_text: 'Customer retains all rights to content shared on Slack.',
      new_text: 'Customer grants Slack a perpetual license to content for service improvement.',
      similarity_score: 0.45,
      risk_level: 'critical',
      risk_score: 95,
      explanation: 'Major IP rights change - Slack now gets perpetual license to your content. This could include proprietary information shared in channels.',
      detected_at: '2024-12-01T09:15:00Z',
    },
    {
      id: 'c8',
      contract_id: '4',
      change_type: 'rewritten',
      clause_category: 'jurisdiction',
      old_text: 'Disputes shall be resolved in courts of customer\'s jurisdiction.',
      new_text: 'All disputes must be resolved through binding arbitration in San Francisco, CA.',
      similarity_score: 0.35,
      risk_level: 'high',
      risk_score: 80,
      explanation: 'Dispute resolution completely changed from your local courts to mandatory arbitration in SF. This significantly limits your legal options.',
      detected_at: '2024-12-01T09:15:00Z',
    },
  ],
  '5': [
    {
      id: 'c9',
      contract_id: '5',
      change_type: 'modified',
      clause_category: 'data_retention',
      old_text: 'Data will be retained for 7 years after account closure.',
      new_text: 'Data will be retained indefinitely for compliance purposes.',
      similarity_score: 0.52,
      risk_level: 'high',
      risk_score: 70,
      explanation: 'Salesforce changed data retention from 7 years to indefinite. This raises privacy concerns and may conflict with GDPR requirements.',
      detected_at: '2024-11-28T10:30:00Z',
    },
  ],
  '6': [
    {
      id: 'c10',
      contract_id: '6',
      change_type: 'added',
      clause_category: 'security',
      old_text: '',
      new_text: 'Customer is responsible for implementing their own encryption at rest.',
      similarity_score: 0,
      risk_level: 'high',
      risk_score: 75,
      explanation: 'MongoDB shifted encryption responsibility to customers. This increases your security obligations and potential liability.',
      detected_at: '2024-12-05T15:20:00Z',
    },
    {
      id: 'c11',
      contract_id: '6',
      change_type: 'modified',
      clause_category: 'backup',
      old_text: 'Automated backups included with all plans.',
      new_text: 'Automated backups available as paid add-on.',
      similarity_score: 0.68,
      risk_level: 'high',
      risk_score: 82,
      explanation: 'Critical service moved from included to paid add-on. This could significantly increase costs and risk data loss if not purchased.',
      detected_at: '2024-12-05T15:20:00Z',
    },
  ],
  '8': [
    {
      id: 'c12',
      contract_id: '8',
      change_type: 'modified',
      clause_category: 'service_level',
      old_text: '99.95% uptime guarantee with 10% monthly credit for violations.',
      new_text: '99.5% uptime guarantee with 5% monthly credit for violations.',
      similarity_score: 0.72,
      risk_level: 'high',
      risk_score: 77,
      explanation: 'SLA downgraded from 99.95% to 99.5% (additional 3.6 hours downtime/month allowed) and credit reduced by half.',
      detected_at: '2024-11-25T16:00:00Z',
    },
  ],
  '10': [
    {
      id: 'c13',
      contract_id: '10',
      change_type: 'added',
      clause_category: 'compliance',
      old_text: '',
      new_text: 'Customer must conduct annual security audits at their own expense.',
      similarity_score: 0,
      risk_level: 'medium',
      risk_score: 55,
      explanation: 'New requirement for annual security audits adds operational burden and cost to your organization.',
      detected_at: '2024-12-14T09:00:00Z',
    },
  ],
};

export const mockStats = {
  total_contracts: 10,
  high_risk_changes: 11,
  monitored_vendors: 10,
  pending_alerts: 5,
  total_changes: 13,
  avg_risk_score: 72,
  contracts_reviewed_this_month: 6,
  upcoming_reviews: 4,
};

export const mockRecentActivity = [
  {
    id: '1',
    type: 'high_risk_change',
    vendor: 'Slack',
    message: 'Critical IP rights change detected',
    timestamp: '2024-12-01T09:15:00Z',
  },
  {
    id: '2',
    type: 'new_version',
    vendor: 'AWS',
    message: 'New version detected with pricing changes',
    timestamp: '2024-12-15T11:20:00Z',
  },
  {
    id: '3',
    type: 'high_risk_change',
    vendor: 'Stripe',
    message: 'SLA guarantee removed',
    timestamp: '2024-12-10T14:30:00Z',
  },
  {
    id: '4',
    type: 'new_contract',
    vendor: 'Auth0',
    message: 'New contract added for monitoring',
    timestamp: '2024-12-14T09:00:00Z',
  },
  {
    id: '5',
    type: 'high_risk_change',
    vendor: 'MongoDB Atlas',
    message: 'Backup policy changed to paid add-on',
    timestamp: '2024-12-05T15:20:00Z',
  },
];

// Analytics data for charts
export const mockRiskTrends = [
  { month: 'Jul', critical: 0, high: 1, medium: 2, low: 0 },
  { month: 'Aug', critical: 0, high: 2, medium: 1, low: 1 },
  { month: 'Sep', critical: 1, high: 1, medium: 3, low: 0 },
  { month: 'Oct', critical: 0, high: 2, medium: 2, low: 1 },
  { month: 'Nov', critical: 1, high: 4, medium: 1, low: 0 },
  { month: 'Dec', critical: 2, high: 6, medium: 2, low: 0 },
];

export const mockCategoryDistribution = [
  { category: 'Liability', count: 2, risk: 85 },
  { category: 'Data Usage', count: 3, risk: 73 },
  { category: 'IP Rights', count: 1, risk: 95 },
  { category: 'Termination', count: 1, risk: 45 },
  { category: 'SLA', count: 2, risk: 87 },
  { category: 'Payment', count: 1, risk: 72 },
  { category: 'Jurisdiction', count: 1, risk: 80 },
  { category: 'Security', count: 1, risk: 75 },
  { category: 'Backup', count: 1, risk: 82 },
];

export const mockVendorRiskScores = [
  { vendor: 'Slack', score: 88, changes: 3, trend: 'up' },
  { vendor: 'Stripe', score: 72, changes: 4, trend: 'up' },
  { vendor: 'MongoDB Atlas', score: 65, changes: 2, trend: 'stable' },
  { vendor: 'Auth0', score: 58, changes: 1, trend: 'down' },
  { vendor: 'Salesforce', score: 52, changes: 1, trend: 'stable' },
  { vendor: 'Zendesk', score: 48, changes: 1, trend: 'down' },
  { vendor: 'AWS', score: 45, changes: 1, trend: 'stable' },
  { vendor: 'Twilio', score: 35, changes: 0, trend: 'stable' },
  { vendor: 'Datadog', score: 32, changes: 0, trend: 'down' },
  { vendor: 'Google Cloud', score: 28, changes: 0, trend: 'down' },
];

export const mockAlerts = [
  {
    id: 'a1',
    contract_id: '4',
    vendor: 'Slack',
    title: 'Critical IP Rights Change',
    description: 'Perpetual license granted to Slack for all content',
    risk_level: 'critical',
    status: 'unread',
    created_at: '2024-12-01T09:15:00Z',
  },
  {
    id: 'a2',
    contract_id: '1',
    vendor: 'Stripe',
    title: 'SLA Guarantee Removed',
    description: '99.9% uptime guarantee has been completely removed',
    risk_level: 'critical',
    status: 'unread',
    created_at: '2024-12-10T14:30:00Z',
  },
  {
    id: 'a3',
    contract_id: '2',
    vendor: 'AWS',
    title: 'Pricing Notice Period Reduced',
    description: 'Price changes now require only 30 days notice instead of 90',
    risk_level: 'high',
    status: 'read',
    created_at: '2024-12-15T11:20:00Z',
  },
  {
    id: 'a4',
    contract_id: '6',
    vendor: 'MongoDB Atlas',
    title: 'Backup Service Now Paid Add-on',
    description: 'Automated backups moved from included to paid service',
    risk_level: 'high',
    status: 'unread',
    created_at: '2024-12-05T15:20:00Z',
  },
  {
    id: 'a5',
    contract_id: '8',
    vendor: 'Zendesk',
    title: 'SLA Downgraded',
    description: 'Uptime guarantee reduced from 99.95% to 99.5%',
    risk_level: 'high',
    status: 'unread',
    created_at: '2024-11-25T16:00:00Z',
  },
];

export const mockComplianceData = [
  { framework: 'GDPR', compliant: 7, non_compliant: 3, pending: 0 },
  { framework: 'SOC 2', compliant: 8, non_compliant: 1, pending: 1 },
  { framework: 'HIPAA', compliant: 5, non_compliant: 2, pending: 3 },
  { framework: 'ISO 27001', compliant: 9, non_compliant: 1, pending: 0 },
];

export const mockTimelineEvents = [
  { date: '2024-12-15', vendor: 'AWS', event: 'Pricing policy updated', type: 'high' },
  { date: '2024-12-14', vendor: 'Auth0', event: 'New compliance requirement added', type: 'medium' },
  { date: '2024-12-12', vendor: 'Twilio', event: 'Policy reviewed - no changes', type: 'low' },
  { date: '2024-12-10', vendor: 'Stripe', event: 'SLA removed', type: 'critical' },
  { date: '2024-12-08', vendor: 'Datadog', event: 'Privacy policy updated', type: 'low' },
  { date: '2024-12-05', vendor: 'MongoDB Atlas', event: 'Backup policy changed', type: 'high' },
  { date: '2024-12-01', vendor: 'Slack', event: 'IP rights modified', type: 'critical' },
  { date: '2024-11-28', vendor: 'Salesforce', event: 'Data retention updated', type: 'high' },
  { date: '2024-11-25', vendor: 'Zendesk', event: 'SLA downgraded', type: 'high' },
];

